# Generated by Django 3.1.7 on 2021-03-17 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishlistUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('image_url', models.URLField(blank=True)),
                ('priority', models.PositiveSmallIntegerField()),
                ('index', models.PositiveSmallIntegerField()),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.link')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.wishlist')),
            ],
            options={
                'unique_together': {('wishlist', 'name')},
            },
        ),
    ]
